// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: protos/user-service/user.proto

package userGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserByClientAccountId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserByClientAccountId) Reset() {
	*x = GetUserByClientAccountId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByClientAccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByClientAccountId) ProtoMessage() {}

func (x *GetUserByClientAccountId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByClientAccountId.ProtoReflect.Descriptor instead.
func (*GetUserByClientAccountId) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{0}
}

type GetUserById struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserById) Reset() {
	*x = GetUserById{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserById) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserById) ProtoMessage() {}

func (x *GetUserById) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserById.ProtoReflect.Descriptor instead.
func (*GetUserById) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{1}
}

type GetConsumerByClientAccountId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetConsumerByClientAccountId) Reset() {
	*x = GetConsumerByClientAccountId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumerByClientAccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerByClientAccountId) ProtoMessage() {}

func (x *GetConsumerByClientAccountId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerByClientAccountId.ProtoReflect.Descriptor instead.
func (*GetConsumerByClientAccountId) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{2}
}

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientAccountId string        `protobuf:"bytes,2,opt,name=clientAccountId,proto3" json:"clientAccountId,omitempty"`
	Name            string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Surname         string        `protobuf:"bytes,4,opt,name=surname,proto3" json:"surname,omitempty"`
	UserName        string        `protobuf:"bytes,5,opt,name=userName,proto3" json:"userName,omitempty"`
	Email           string        `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone           string        `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Company         string        `protobuf:"bytes,8,opt,name=company,proto3" json:"company,omitempty"`
	Type            string        `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Avatar          string        `protobuf:"bytes,10,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Setting         *User_Setting `protobuf:"bytes,11,opt,name=setting,proto3" json:"setting,omitempty"`
	CreatedAt       string        `protobuf:"bytes,12,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt       string        `protobuf:"bytes,13,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	Locale          string        `protobuf:"bytes,14,opt,name=locale,proto3" json:"locale,omitempty"`
	Currency        string        `protobuf:"bytes,15,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetClientAccountId() string {
	if x != nil {
		return x.ClientAccountId
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *User) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetSetting() *User_Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

func (x *User) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *User) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *User) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *User) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type RegisterConsumer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterConsumer) Reset() {
	*x = RegisterConsumer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterConsumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumer) ProtoMessage() {}

func (x *RegisterConsumer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumer.ProtoReflect.Descriptor instead.
func (*RegisterConsumer) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{4}
}

type UpdateConsumer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateConsumer) Reset() {
	*x = UpdateConsumer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConsumer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConsumer) ProtoMessage() {}

func (x *UpdateConsumer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConsumer.ProtoReflect.Descriptor instead.
func (*UpdateConsumer) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{5}
}

type GetSellerByClientAccountId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSellerByClientAccountId) Reset() {
	*x = GetSellerByClientAccountId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSellerByClientAccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerByClientAccountId) ProtoMessage() {}

func (x *GetSellerByClientAccountId) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerByClientAccountId.ProtoReflect.Descriptor instead.
func (*GetSellerByClientAccountId) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{6}
}

type RegisterSeller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RegisterSeller) Reset() {
	*x = RegisterSeller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterSeller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSeller) ProtoMessage() {}

func (x *RegisterSeller) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSeller.ProtoReflect.Descriptor instead.
func (*RegisterSeller) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{7}
}

type UpdateSeller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSeller) Reset() {
	*x = UpdateSeller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSeller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeller) ProtoMessage() {}

func (x *UpdateSeller) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeller.ProtoReflect.Descriptor instead.
func (*UpdateSeller) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{8}
}

type UpdateSellerSetting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSellerSetting) Reset() {
	*x = UpdateSellerSetting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSellerSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSellerSetting) ProtoMessage() {}

func (x *UpdateSellerSetting) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSellerSetting.ProtoReflect.Descriptor instead.
func (*UpdateSellerSetting) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{9}
}

type GetSellersByTags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSellersByTags) Reset() {
	*x = GetSellersByTags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSellersByTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellersByTags) ProtoMessage() {}

func (x *GetSellersByTags) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellersByTags.ProtoReflect.Descriptor instead.
func (*GetSellersByTags) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{10}
}

type Sort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderBy   string `protobuf:"bytes,1,opt,name=orderBy,proto3" json:"orderBy,omitempty"`
	OrderName string `protobuf:"bytes,2,opt,name=orderName,proto3" json:"orderName,omitempty"`
}

func (x *Sort) Reset() {
	*x = Sort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sort) ProtoMessage() {}

func (x *Sort) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sort.ProtoReflect.Descriptor instead.
func (*Sort) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{11}
}

func (x *Sort) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *Sort) GetOrderName() string {
	if x != nil {
		return x.OrderName
	}
	return ""
}

type PageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page           int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage        int32 `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	TotalCount     int32 `protobuf:"varint,3,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	TotalPageCount int32 `protobuf:"varint,4,opt,name=totalPageCount,proto3" json:"totalPageCount,omitempty"`
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{12}
}

func (x *PageInfo) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PageInfo) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *PageInfo) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *PageInfo) GetTotalPageCount() int32 {
	if x != nil {
		return x.TotalPageCount
	}
	return 0
}

type GetUsersList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUsersList) Reset() {
	*x = GetUsersList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersList) ProtoMessage() {}

func (x *GetUsersList) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersList.ProtoReflect.Descriptor instead.
func (*GetUsersList) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{13}
}

type GetUserByClientAccountId_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAccountId string `protobuf:"bytes,1,opt,name=clientAccountId,proto3" json:"clientAccountId,omitempty"`
}

func (x *GetUserByClientAccountId_Request) Reset() {
	*x = GetUserByClientAccountId_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByClientAccountId_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByClientAccountId_Request) ProtoMessage() {}

func (x *GetUserByClientAccountId_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByClientAccountId_Request.ProtoReflect.Descriptor instead.
func (*GetUserByClientAccountId_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GetUserByClientAccountId_Request) GetClientAccountId() string {
	if x != nil {
		return x.ClientAccountId
	}
	return ""
}

type GetUserByClientAccountId_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetUserByClientAccountId_Response) Reset() {
	*x = GetUserByClientAccountId_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserByClientAccountId_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByClientAccountId_Response) ProtoMessage() {}

func (x *GetUserByClientAccountId_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByClientAccountId_Response.ProtoReflect.Descriptor instead.
func (*GetUserByClientAccountId_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{0, 1}
}

func (x *GetUserByClientAccountId_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserById_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetUserById_Request) Reset() {
	*x = GetUserById_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserById_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserById_Request) ProtoMessage() {}

func (x *GetUserById_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserById_Request.ProtoReflect.Descriptor instead.
func (*GetUserById_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetUserById_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserById_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetUserById_Response) Reset() {
	*x = GetUserById_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserById_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserById_Response) ProtoMessage() {}

func (x *GetUserById_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserById_Response.ProtoReflect.Descriptor instead.
func (*GetUserById_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{1, 1}
}

func (x *GetUserById_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetConsumerByClientAccountId_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAccountId string `protobuf:"bytes,1,opt,name=clientAccountId,proto3" json:"clientAccountId,omitempty"`
}

func (x *GetConsumerByClientAccountId_Request) Reset() {
	*x = GetConsumerByClientAccountId_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumerByClientAccountId_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerByClientAccountId_Request) ProtoMessage() {}

func (x *GetConsumerByClientAccountId_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerByClientAccountId_Request.ProtoReflect.Descriptor instead.
func (*GetConsumerByClientAccountId_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GetConsumerByClientAccountId_Request) GetClientAccountId() string {
	if x != nil {
		return x.ClientAccountId
	}
	return ""
}

type GetConsumerByClientAccountId_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetConsumerByClientAccountId_Response) Reset() {
	*x = GetConsumerByClientAccountId_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConsumerByClientAccountId_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConsumerByClientAccountId_Response) ProtoMessage() {}

func (x *GetConsumerByClientAccountId_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConsumerByClientAccountId_Response.ProtoReflect.Descriptor instead.
func (*GetConsumerByClientAccountId_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{2, 1}
}

func (x *GetConsumerByClientAccountId_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type User_Setting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags   []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Emails bool     `protobuf:"varint,3,opt,name=emails,proto3" json:"emails,omitempty"`
}

func (x *User_Setting) Reset() {
	*x = User_Setting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User_Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User_Setting) ProtoMessage() {}

func (x *User_Setting) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User_Setting.ProtoReflect.Descriptor instead.
func (*User_Setting) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{3, 0}
}

func (x *User_Setting) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User_Setting) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *User_Setting) GetEmails() bool {
	if x != nil {
		return x.Emails
	}
	return false
}

type RegisterConsumer_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *RegisterConsumer_Request) Reset() {
	*x = RegisterConsumer_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterConsumer_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumer_Request) ProtoMessage() {}

func (x *RegisterConsumer_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumer_Request.ProtoReflect.Descriptor instead.
func (*RegisterConsumer_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{4, 0}
}

func (x *RegisterConsumer_Request) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterConsumer_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
}

func (x *RegisterConsumer_Response) Reset() {
	*x = RegisterConsumer_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterConsumer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterConsumer_Response) ProtoMessage() {}

func (x *RegisterConsumer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterConsumer_Response.ProtoReflect.Descriptor instead.
func (*RegisterConsumer_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{4, 1}
}

func (x *RegisterConsumer_Response) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type UpdateConsumer_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAccountId string `protobuf:"bytes,1,opt,name=clientAccountId,proto3" json:"clientAccountId,omitempty"`
	Surname         string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Name            string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Company         string `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	Phone           string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	UserName        string `protobuf:"bytes,6,opt,name=userName,proto3" json:"userName,omitempty"`
	Avatar          string `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Locale          string `protobuf:"bytes,8,opt,name=locale,proto3" json:"locale,omitempty"`
	Currency        string `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *UpdateConsumer_Request) Reset() {
	*x = UpdateConsumer_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConsumer_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConsumer_Request) ProtoMessage() {}

func (x *UpdateConsumer_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConsumer_Request.ProtoReflect.Descriptor instead.
func (*UpdateConsumer_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{5, 0}
}

func (x *UpdateConsumer_Request) GetClientAccountId() string {
	if x != nil {
		return x.ClientAccountId
	}
	return ""
}

func (x *UpdateConsumer_Request) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *UpdateConsumer_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateConsumer_Request) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateConsumer_Request) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateConsumer_Request) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateConsumer_Request) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateConsumer_Request) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *UpdateConsumer_Request) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type UpdateConsumer_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UpdateConsumer_Response) Reset() {
	*x = UpdateConsumer_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConsumer_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConsumer_Response) ProtoMessage() {}

func (x *UpdateConsumer_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConsumer_Response.ProtoReflect.Descriptor instead.
func (*UpdateConsumer_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{5, 1}
}

func (x *UpdateConsumer_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetSellerByClientAccountId_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAccountId string `protobuf:"bytes,1,opt,name=clientAccountId,proto3" json:"clientAccountId,omitempty"`
}

func (x *GetSellerByClientAccountId_Request) Reset() {
	*x = GetSellerByClientAccountId_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSellerByClientAccountId_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerByClientAccountId_Request) ProtoMessage() {}

func (x *GetSellerByClientAccountId_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerByClientAccountId_Request.ProtoReflect.Descriptor instead.
func (*GetSellerByClientAccountId_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{6, 0}
}

func (x *GetSellerByClientAccountId_Request) GetClientAccountId() string {
	if x != nil {
		return x.ClientAccountId
	}
	return ""
}

type GetSellerByClientAccountId_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *GetSellerByClientAccountId_Response) Reset() {
	*x = GetSellerByClientAccountId_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSellerByClientAccountId_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerByClientAccountId_Response) ProtoMessage() {}

func (x *GetSellerByClientAccountId_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerByClientAccountId_Response.ProtoReflect.Descriptor instead.
func (*GetSellerByClientAccountId_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{6, 1}
}

func (x *GetSellerByClientAccountId_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterSeller_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *RegisterSeller_Request) Reset() {
	*x = RegisterSeller_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterSeller_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSeller_Request) ProtoMessage() {}

func (x *RegisterSeller_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSeller_Request.ProtoReflect.Descriptor instead.
func (*RegisterSeller_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{7, 0}
}

func (x *RegisterSeller_Request) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterSeller_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
}

func (x *RegisterSeller_Response) Reset() {
	*x = RegisterSeller_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterSeller_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSeller_Response) ProtoMessage() {}

func (x *RegisterSeller_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSeller_Response.ProtoReflect.Descriptor instead.
func (*RegisterSeller_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{7, 1}
}

func (x *RegisterSeller_Response) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type UpdateSeller_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientAccountId string `protobuf:"bytes,1,opt,name=clientAccountId,proto3" json:"clientAccountId,omitempty"`
	Surname         string `protobuf:"bytes,2,opt,name=surname,proto3" json:"surname,omitempty"`
	Name            string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Company         string `protobuf:"bytes,4,opt,name=company,proto3" json:"company,omitempty"`
	Phone           string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	UserName        string `protobuf:"bytes,6,opt,name=userName,proto3" json:"userName,omitempty"`
	Avatar          string `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Locale          string `protobuf:"bytes,8,opt,name=locale,proto3" json:"locale,omitempty"`
	Emails          bool   `protobuf:"varint,9,opt,name=emails,proto3" json:"emails,omitempty"`
	Currency        string `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *UpdateSeller_Request) Reset() {
	*x = UpdateSeller_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSeller_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeller_Request) ProtoMessage() {}

func (x *UpdateSeller_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeller_Request.ProtoReflect.Descriptor instead.
func (*UpdateSeller_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{8, 0}
}

func (x *UpdateSeller_Request) GetClientAccountId() string {
	if x != nil {
		return x.ClientAccountId
	}
	return ""
}

func (x *UpdateSeller_Request) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

func (x *UpdateSeller_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSeller_Request) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateSeller_Request) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateSeller_Request) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UpdateSeller_Request) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateSeller_Request) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *UpdateSeller_Request) GetEmails() bool {
	if x != nil {
		return x.Emails
	}
	return false
}

func (x *UpdateSeller_Request) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type UpdateSeller_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *UpdateSeller_Response) Reset() {
	*x = UpdateSeller_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSeller_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSeller_Response) ProtoMessage() {}

func (x *UpdateSeller_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSeller_Response.ProtoReflect.Descriptor instead.
func (*UpdateSeller_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{8, 1}
}

func (x *UpdateSeller_Response) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateSellerSetting_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string        `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Setting *User_Setting `protobuf:"bytes,2,opt,name=setting,proto3" json:"setting,omitempty"`
}

func (x *UpdateSellerSetting_Request) Reset() {
	*x = UpdateSellerSetting_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSellerSetting_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSellerSetting_Request) ProtoMessage() {}

func (x *UpdateSellerSetting_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSellerSetting_Request.ProtoReflect.Descriptor instead.
func (*UpdateSellerSetting_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{9, 0}
}

func (x *UpdateSellerSetting_Request) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateSellerSetting_Request) GetSetting() *User_Setting {
	if x != nil {
		return x.Setting
	}
	return nil
}

type UpdateSellerSetting_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsSuccess bool `protobuf:"varint,2,opt,name=isSuccess,proto3" json:"isSuccess,omitempty"`
}

func (x *UpdateSellerSetting_Response) Reset() {
	*x = UpdateSellerSetting_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSellerSetting_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSellerSetting_Response) ProtoMessage() {}

func (x *UpdateSellerSetting_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSellerSetting_Response.ProtoReflect.Descriptor instead.
func (*UpdateSellerSetting_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{9, 1}
}

func (x *UpdateSellerSetting_Response) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type GetSellersByTags_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tags []string `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *GetSellersByTags_Request) Reset() {
	*x = GetSellersByTags_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSellersByTags_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellersByTags_Request) ProtoMessage() {}

func (x *GetSellersByTags_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellersByTags_Request.ProtoReflect.Descriptor instead.
func (*GetSellersByTags_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{10, 0}
}

func (x *GetSellersByTags_Request) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetSellersByTags_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Users []*User `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *GetSellersByTags_Response) Reset() {
	*x = GetSellersByTags_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSellersByTags_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellersByTags_Response) ProtoMessage() {}

func (x *GetSellersByTags_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellersByTags_Response.ProtoReflect.Descriptor instead.
func (*GetSellersByTags_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{10, 1}
}

func (x *GetSellersByTags_Response) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUsersList_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page    int32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage int32   `protobuf:"varint,2,opt,name=perPage,proto3" json:"perPage,omitempty"`
	Sort    []*Sort `protobuf:"bytes,6,rep,name=sort,proto3" json:"sort,omitempty"`
}

func (x *GetUsersList_Request) Reset() {
	*x = GetUsersList_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersList_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersList_Request) ProtoMessage() {}

func (x *GetUsersList_Request) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersList_Request.ProtoReflect.Descriptor instead.
func (*GetUsersList_Request) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{13, 0}
}

func (x *GetUsersList_Request) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUsersList_Request) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

func (x *GetUsersList_Request) GetSort() []*Sort {
	if x != nil {
		return x.Sort
	}
	return nil
}

type GetUsersList_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []*User   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	PageInfo *PageInfo `protobuf:"bytes,2,opt,name=pageInfo,proto3" json:"pageInfo,omitempty"`
}

func (x *GetUsersList_Response) Reset() {
	*x = GetUsersList_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_user_service_user_proto_msgTypes[36]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUsersList_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersList_Response) ProtoMessage() {}

func (x *GetUsersList_Response) ProtoReflect() protoreflect.Message {
	mi := &file_protos_user_service_user_proto_msgTypes[36]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersList_Response.ProtoReflect.Descriptor instead.
func (*GetUsersList_Response) Descriptor() ([]byte, []int) {
	return file_protos_user_service_user_proto_rawDescGZIP(), []int{13, 1}
}

func (x *GetUsersList_Response) GetData() []*User {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetUsersList_Response) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

var File_protos_user_service_user_proto protoreflect.FileDescriptor

var file_protos_user_service_user_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x82, 0x01,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x33, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a,
	0x31, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x22, 0x63, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49,
	0x64, 0x1a, 0x21, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x1a, 0x31, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x86, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x33, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x31, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72,
	0x22, 0xe8, 0x03, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12,
	0x33, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18,
	0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x79, 0x1a, 0x45, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74,
	0x61, 0x67, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x6e, 0x0a, 0x10, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x1a,
	0x30, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x1a, 0x28, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0xbf, 0x02, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x1a, 0xf9,
	0x01, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x1a, 0x31, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x84, 0x01,
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x1a, 0x33, 0x0a, 0x07,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x1a, 0x31, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x22, 0x6c, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x30, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x28, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0xd5, 0x02, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c,
	0x6c, 0x65, 0x72, 0x1a, 0x91, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x28, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x6f, 0x63,
	0x61, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x1a, 0x31, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x97, 0x01, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x1a, 0x56, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x33, 0x0a, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x07, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x1a, 0x28, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x53, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x22, 0x66, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x73, 0x1a, 0x1d, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x1a, 0x33, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x22, 0x3e, 0x0a, 0x04,
	0x53, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x42, 0x79, 0x12, 0x1c,
	0x0a, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x80, 0x01, 0x0a,
	0x08, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0e, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0xd4, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74,
	0x1a, 0x5e, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x70, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x73, 0x6f, 0x72,
	0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x1a, 0x64, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x12, 0x31, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x70, 0x61,
	0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x32, 0xff, 0x08, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x79, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x2d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x52, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64,
	0x12, 0x20, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x42, 0x79, 0x49, 0x64, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x85, 0x01, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x31, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x32, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x75,
	0x6d, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a,
	0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x12, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5b, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x12, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7f, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6c,
	0x6c, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65,
	0x6c, 0x6c, 0x65, 0x72, 0x42, 0x79, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x42, 0x79, 0x54, 0x61,
	0x67, 0x73, 0x12, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67,
	0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x73, 0x42, 0x79, 0x54, 0x61, 0x67, 0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x6c,
	0x6c, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55,
	0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x21,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6a, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x55, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x12, 0x21, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_user_service_user_proto_rawDescOnce sync.Once
	file_protos_user_service_user_proto_rawDescData = file_protos_user_service_user_proto_rawDesc
)

func file_protos_user_service_user_proto_rawDescGZIP() []byte {
	file_protos_user_service_user_proto_rawDescOnce.Do(func() {
		file_protos_user_service_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_user_service_user_proto_rawDescData)
	})
	return file_protos_user_service_user_proto_rawDescData
}

var file_protos_user_service_user_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_protos_user_service_user_proto_goTypes = []interface{}{
	(*GetUserByClientAccountId)(nil),              // 0: userService.GetUserByClientAccountId
	(*GetUserById)(nil),                           // 1: userService.GetUserById
	(*GetConsumerByClientAccountId)(nil),          // 2: userService.GetConsumerByClientAccountId
	(*User)(nil),                                  // 3: userService.User
	(*RegisterConsumer)(nil),                      // 4: userService.RegisterConsumer
	(*UpdateConsumer)(nil),                        // 5: userService.UpdateConsumer
	(*GetSellerByClientAccountId)(nil),            // 6: userService.GetSellerByClientAccountId
	(*RegisterSeller)(nil),                        // 7: userService.RegisterSeller
	(*UpdateSeller)(nil),                          // 8: userService.UpdateSeller
	(*UpdateSellerSetting)(nil),                   // 9: userService.UpdateSellerSetting
	(*GetSellersByTags)(nil),                      // 10: userService.GetSellersByTags
	(*Sort)(nil),                                  // 11: userService.Sort
	(*PageInfo)(nil),                              // 12: userService.PageInfo
	(*GetUsersList)(nil),                          // 13: userService.GetUsersList
	(*GetUserByClientAccountId_Request)(nil),      // 14: userService.GetUserByClientAccountId.Request
	(*GetUserByClientAccountId_Response)(nil),     // 15: userService.GetUserByClientAccountId.Response
	(*GetUserById_Request)(nil),                   // 16: userService.GetUserById.Request
	(*GetUserById_Response)(nil),                  // 17: userService.GetUserById.Response
	(*GetConsumerByClientAccountId_Request)(nil),  // 18: userService.GetConsumerByClientAccountId.Request
	(*GetConsumerByClientAccountId_Response)(nil), // 19: userService.GetConsumerByClientAccountId.Response
	(*User_Setting)(nil),                          // 20: userService.User.Setting
	(*RegisterConsumer_Request)(nil),              // 21: userService.RegisterConsumer.Request
	(*RegisterConsumer_Response)(nil),             // 22: userService.RegisterConsumer.Response
	(*UpdateConsumer_Request)(nil),                // 23: userService.UpdateConsumer.Request
	(*UpdateConsumer_Response)(nil),               // 24: userService.UpdateConsumer.Response
	(*GetSellerByClientAccountId_Request)(nil),    // 25: userService.GetSellerByClientAccountId.Request
	(*GetSellerByClientAccountId_Response)(nil),   // 26: userService.GetSellerByClientAccountId.Response
	(*RegisterSeller_Request)(nil),                // 27: userService.RegisterSeller.Request
	(*RegisterSeller_Response)(nil),               // 28: userService.RegisterSeller.Response
	(*UpdateSeller_Request)(nil),                  // 29: userService.UpdateSeller.Request
	(*UpdateSeller_Response)(nil),                 // 30: userService.UpdateSeller.Response
	(*UpdateSellerSetting_Request)(nil),           // 31: userService.UpdateSellerSetting.Request
	(*UpdateSellerSetting_Response)(nil),          // 32: userService.UpdateSellerSetting.Response
	(*GetSellersByTags_Request)(nil),              // 33: userService.GetSellersByTags.Request
	(*GetSellersByTags_Response)(nil),             // 34: userService.GetSellersByTags.Response
	(*GetUsersList_Request)(nil),                  // 35: userService.GetUsersList.Request
	(*GetUsersList_Response)(nil),                 // 36: userService.GetUsersList.Response
}
var file_protos_user_service_user_proto_depIdxs = []int32{
	20, // 0: userService.User.setting:type_name -> userService.User.Setting
	3,  // 1: userService.GetUserByClientAccountId.Response.user:type_name -> userService.User
	3,  // 2: userService.GetUserById.Response.user:type_name -> userService.User
	3,  // 3: userService.GetConsumerByClientAccountId.Response.user:type_name -> userService.User
	3,  // 4: userService.RegisterConsumer.Request.user:type_name -> userService.User
	3,  // 5: userService.UpdateConsumer.Response.user:type_name -> userService.User
	3,  // 6: userService.GetSellerByClientAccountId.Response.user:type_name -> userService.User
	3,  // 7: userService.RegisterSeller.Request.user:type_name -> userService.User
	3,  // 8: userService.UpdateSeller.Response.user:type_name -> userService.User
	20, // 9: userService.UpdateSellerSetting.Request.setting:type_name -> userService.User.Setting
	3,  // 10: userService.GetSellersByTags.Response.users:type_name -> userService.User
	11, // 11: userService.GetUsersList.Request.sort:type_name -> userService.Sort
	3,  // 12: userService.GetUsersList.Response.data:type_name -> userService.User
	12, // 13: userService.GetUsersList.Response.pageInfo:type_name -> userService.PageInfo
	14, // 14: userService.UserService.GetUserByClientAccountId:input_type -> userService.GetUserByClientAccountId.Request
	16, // 15: userService.UserService.GetUserById:input_type -> userService.GetUserById.Request
	18, // 16: userService.UserService.GetConsumerByClientAccountId:input_type -> userService.GetConsumerByClientAccountId.Request
	21, // 17: userService.UserService.RegisterConsumer:input_type -> userService.RegisterConsumer.Request
	23, // 18: userService.UserService.UpdateConsumer:input_type -> userService.UpdateConsumer.Request
	25, // 19: userService.UserService.GetSellerByClientAccountId:input_type -> userService.GetSellerByClientAccountId.Request
	33, // 20: userService.UserService.GetSellersByTags:input_type -> userService.GetSellersByTags.Request
	27, // 21: userService.UserService.RegisterSeller:input_type -> userService.RegisterSeller.Request
	29, // 22: userService.UserService.UpdateSeller:input_type -> userService.UpdateSeller.Request
	31, // 23: userService.UserService.UpdateSellerSetting:input_type -> userService.UpdateSellerSetting.Request
	35, // 24: userService.UserService.GetUsersList:input_type -> userService.GetUsersList.Request
	15, // 25: userService.UserService.GetUserByClientAccountId:output_type -> userService.GetUserByClientAccountId.Response
	17, // 26: userService.UserService.GetUserById:output_type -> userService.GetUserById.Response
	19, // 27: userService.UserService.GetConsumerByClientAccountId:output_type -> userService.GetConsumerByClientAccountId.Response
	22, // 28: userService.UserService.RegisterConsumer:output_type -> userService.RegisterConsumer.Response
	24, // 29: userService.UserService.UpdateConsumer:output_type -> userService.UpdateConsumer.Response
	26, // 30: userService.UserService.GetSellerByClientAccountId:output_type -> userService.GetSellerByClientAccountId.Response
	34, // 31: userService.UserService.GetSellersByTags:output_type -> userService.GetSellersByTags.Response
	28, // 32: userService.UserService.RegisterSeller:output_type -> userService.RegisterSeller.Response
	30, // 33: userService.UserService.UpdateSeller:output_type -> userService.UpdateSeller.Response
	32, // 34: userService.UserService.UpdateSellerSetting:output_type -> userService.UpdateSellerSetting.Response
	36, // 35: userService.UserService.GetUsersList:output_type -> userService.GetUsersList.Response
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protos_user_service_user_proto_init() }
func file_protos_user_service_user_proto_init() {
	if File_protos_user_service_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_user_service_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByClientAccountId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserById); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumerByClientAccountId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterConsumer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConsumer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSellerByClientAccountId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterSeller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSeller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSellerSetting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSellersByTags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByClientAccountId_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserByClientAccountId_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserById_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserById_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumerByClientAccountId_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetConsumerByClientAccountId_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User_Setting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterConsumer_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterConsumer_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConsumer_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateConsumer_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSellerByClientAccountId_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSellerByClientAccountId_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterSeller_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterSeller_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSeller_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSeller_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSellerSetting_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSellerSetting_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSellersByTags_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSellersByTags_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersList_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_user_service_user_proto_msgTypes[36].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUsersList_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_user_service_user_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_user_service_user_proto_goTypes,
		DependencyIndexes: file_protos_user_service_user_proto_depIdxs,
		MessageInfos:      file_protos_user_service_user_proto_msgTypes,
	}.Build()
	File_protos_user_service_user_proto = out.File
	file_protos_user_service_user_proto_rawDesc = nil
	file_protos_user_service_user_proto_goTypes = nil
	file_protos_user_service_user_proto_depIdxs = nil
}
