version: "3.7"
services:
  auth-database:
    image: postgres
    container_name: auth-service-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH}
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}
    ports:
      - ${POSTGRES_PORT_AUTH}:${POSTGRES_PORT_AUTH}
    volumes:
      - auth-service:/var/lib/postgresql/data
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    depends_on:
      - auth-database
    networks:
      - default
    ports:
      - ${PORT_AUTH_SERVICE}:${PORT_AUTH_SERVICE}
    expose:
      - ${PORT_AUTH_SERVICE}
        #  grafana:
  #    container_name: grafana_container
  #    image: grafana/grafana
  #    ports:
  #      - '3000:3000'
  #
#  jaeger:
#    restart: always
#    image: jaegertracing/all-in-one:1.21
#    ports:
#      - 16686:16686
#      - 14268:14268
#    networks:
#      - default
volumes:
  auth-service:
