// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	auth "auth-service/pkg/auth"

	mock "github.com/stretchr/testify/mock"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// CreateAuth provides a mock function with given fields: _a0
func (_m *AuthRepository) CreateAuth(_a0 auth.Auth) (auth.Auth, error) {
	ret := _m.Called(_a0)

	var r0 auth.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(auth.Auth) (auth.Auth, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(auth.Auth) auth.Auth); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(auth.Auth)
	}

	if rf, ok := ret.Get(1).(func(auth.Auth) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAuth provides a mock function with given fields: id
func (_m *AuthRepository) DeleteAuth(id string) {
	_m.Called(id)
}

// FetchAuth provides a mock function with given fields: id, email
func (_m *AuthRepository) FetchAuth(id string, email string) (auth.Auth, error) {
	ret := _m.Called(id, email)

	var r0 auth.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (auth.Auth, error)); ok {
		return rf(id, email)
	}
	if rf, ok := ret.Get(0).(func(string, string) auth.Auth); ok {
		r0 = rf(id, email)
	} else {
		r0 = ret.Get(0).(auth.Auth)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAuth provides a mock function with given fields: id, _a1
func (_m *AuthRepository) UpdateAuth(id string, _a1 auth.Auth) (auth.Auth, error) {
	ret := _m.Called(id, _a1)

	var r0 auth.Auth
	var r1 error
	if rf, ok := ret.Get(0).(func(string, auth.Auth) (auth.Auth, error)); ok {
		return rf(id, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, auth.Auth) auth.Auth); ok {
		r0 = rf(id, _a1)
	} else {
		r0 = ret.Get(0).(auth.Auth)
	}

	if rf, ok := ret.Get(1).(func(string, auth.Auth) error); ok {
		r1 = rf(id, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
