// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QueueService is an autogenerated mock type for the QueueService type
type QueueService struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *QueueService) Close() {
	_m.Called()
}

// SendMsg provides a mock function with given fields: msg
func (_m *QueueService) SendMsg(msg string) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewQueueService creates a new instance of QueueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQueueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *QueueService {
	mock := &QueueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
